[package]
name = "pages"
authors = ["Parth-bathe0142 <parth.bathe0142@gmail.com>"]
description = "Personal portfolio"
version = "0.1.0"
rust-version = "1.78"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
askama = { workspace = true }
spin-sdk = { workspace = true }
http = { workspace = true }
shared = { version = "0.1.0", path = "../shared" }
